### ISSUE TITLE
How to add gender and DOB also 

### ISSUE THREAD

**Issue by Shalini201** [atharvakale31/Face_Recognition_Android#11]
Hi Atharva Sir,

Im trying to implement this for college project. But I want the user to enter his DOB and gender also. And I want to save these details along with his name. Can you please help me with how to add these fields as In pretty new to adnroid development. 

Thanks again sir.

**Comment by atharvakale31** [comment]
Hey, I am glad that it helped. Adding new fields should be fairly straightforward. You can remove the way we are taking the Name input, and just put 2-3 text fields below face preview to take extra inputs. As you are new to Android development, I would suggest you start building your android app from scratch and use this app as a reference. That way it would be much easier to customize it the way you want. (Editing someones else's code can be pretty confusing sometimes).
