### ISSUE TITLE
How to save the faces into a table in mariadb?

### ISSUE THREAD

**Issue by ajinliu** [atharvakale31/Face_Recognition_Android#12]
Hello. I'm excited for your great hard work. I do like the project to have the capabilitie to save the faces to an database's table in MariaDB or MySql instead of the shared preferences, due the need for adding not just only me but many people will use your wonderful app. Thus sometimes i will change my phone or maybe by hard reseting will delete all the faces saved. So please. Can you share some code for it? Thank you.

**Comment by atharvakale31** [comment]
Hey, I am glad that it helped. Even I would like it if the faces get stored in a database of some sort. Sadly I don't have the working knowledge of these databases with android ( I can make it work for firebase though). Make sure that you know how the current faces are stored (its a json) and you will be good to go.

**Comment by ajinliu** [comment]
do you like that i make a pull request for storing the databank into a database?

**Comment by ajinliu** [comment]
I need this app for running on linux. No matter if it written in Java or Python. Could you point me to the right way? Thank you.

**Comment by atharvakale31** [comment]
Sure!! make your own version and I would gladly refer to it in the readme.

**Comment by lionheart83** [comment]
> do you like that i make a pull request for storing the databank into a database?

Hello sir, would you like share the code with me please

**Comment by ajinliu** [comment]
Still in process... Stay tuned.

**Comment by lionheart83** [comment]
> Still in process... Stay tuned.

Ahh sure ... This would be greaatt!
