### ISSUE TITLE
Randomly restart the phone!

### ISSUE THREAD

**Issue by ajinliu** [atharvakale31/Face_Recognition_Android#13]
Don't know how to reproduce it. No chance for debug it.

**Comment by atharvakale31** [comment]
Do let me know when you can reproduce it.(Just the steps on the phone)

**Comment by ajinliu** [comment]
Sorry budie, Seems i need to buy a new phone. It's gone crazy. No think nothing concerning about your project. Please forgive.

**Comment by atharvakale31** [comment]
XD no worries man.
