### ISSUE TITLE
Sometimes wrong name is shown for a person.

### ISSUE THREAD

**Issue by Shalini201** [atharvakale31/Face_Recognition_Android#14]
Hi Sir,
Sometimes the recognition is wrong, for example personA is recognized as personC. Is there any cutoff score of percentage confidence or probability, so that we can show the name only when its confidence is lets say "more than 90%" ?

**Comment by atharvakale31** [comment]
Hey,
Yes, there is a cutoff parameter that you can tune. It is the nearest neighbor distance.
https://github.com/atharvakale31/Real-Time_Face_Recognition_Android/blob/master/app/src/main/java/com/atharvakale/facerecognition/MainActivity.java#L632
This link will take you to that line.

**Comment by Shalini201** [comment]
Thanks Sir,
So is it like , the lower the distance score the better the match ?

**Comment by atharvakale31** [comment]
Yes
