### ISSUE TITLE
Face Database Import From Mysql

### ISSUE THREAD

**Issue by lionheart83** [atharvakale31/Face_Recognition_Android#15]
Is it possible recognize face download from mysql database? Please help sir!

**Comment by atharvakale31** [comment]
Yes, it is possible, you will have to save and retrieve the face embeddings from the MySQL database rather than shared preferences.

**Comment by lionheart83** [comment]
how about displaying predictions using this tensorflow?

**Comment by atharvakale31** [comment]
Sorry, I did not understand, Can you elaborate? We are already using Tensorflow Lite.
