### ISSUE TITLE
Its matching unknown face as my face

### ISSUE THREAD

**Issue by Kant01354** [atharvakale31/Face_Recognition_Android#16]
Hi atharva,

The app is really good but it is matching unknown face as my face. I have added only my record/face. But when i hover the camera on unknown face it recognizes them as my face.
How to introduce a cutoff so that it doesnt match any face randomly with low accuracy.
Please help

**Comment by ersaurabh101** [comment]
Hello, I need 1 paid support if you as developer is interested. Please connect me on whatsapp +919216142737

**Comment by atharvakale31** [comment]
Hey @Kant01354 ,
Yes, there is a cutoff parameter that you can tune. It is the nearest neighbor distance.
https://github.com/atharvakale31/Real-Time_Face_Recognition_Android/blob/master/app/src/main/java/com/atharvakale/facerecognition/MainActivity.java#L632
This link will take you to that line.
