### ISSUE TITLE
Stored Faces automatically remove once we close the application and start again

### ISSUE THREAD

**Issue by nikhilpawar151** [atharvakale31/Face_Recognition_Android#18]
Hello, @atharvakale31 thanks for your code. I checked your code and it works fine. Great work.

When I execute your code, it works fine for the first time when we store any face and are able to recognize the face. But when I close the app then the previously stored face cannot be recognized again. I have to store the face again and again for each session. Can you tell me if there is any way to store the face for at least a certain time interval?

**Comment by atharvakale31** [comment]
Hey @nikhilpawar151,
Thanks!
After you add faces to the app, please click on **Save Recognitions** in **Actions** tab. Then you won't have to store the faces again during each new session.
