### ISSUE TITLE
Face is Recognized from Image how to disable it

### ISSUE THREAD

**Issue by Nareshthakor** [atharvakale31/Face_Recognition_Android#19]
The app is really good but one of the problem i am facing with is i have add face with real user face and scan it to user image then Face Scan Recognized from Image. 
How to Disable face scan form image. i have only scan real face scan form camera. 
Please help

**Comment by atharvakale31** [comment]
Hey @Nareshthakor,
Currently, we use Google's ML kit for face detection, it does not have a feature to detect the liveliness of the face. Hence as of now you cannot disable scanning of a face from an image. This problem could be solved by using a face liveliness detection model before the face recognition model.

**Comment by Nareshthakor** [comment]
Thank you for your response.

**Comment by rsingh2083** [comment]
> Thank you for your response.

Hi Naresh how did you solve this problem can you please suggest ?
