### ISSUE TITLE
Overall UI imrovement

### ISSUE THREAD

**Issue by binayshaw7777** [atharvakale31/Face_Recognition_Android#21]
I would like to contribute to your project!

**Comment by atharvakale31** [comment]
Hey @binayshaw7777,
Glad to hear that! 
Any specific ideas in mind?

**Comment by binayshaw7777** [comment]
> 

Yeah, I've few. I'll share some of my design links to you.

By the way is there any other way to contact you? I've some questions regarding your project. So that'll be really helpful to me.

My Email : binayshaw7777@gmail.com

**Comment by binayshaw7777** [comment]
> Hey @binayshaw7777, Glad to hear that! Any specific ideas in mind?

also can you check the mail I sent you.

**Comment by roshannsharma** [comment]
I want contact you my email id: roshansharmakurma@gmail.com
