### ISSUE TITLE
Design New Logo for the App

### ISSUE THREAD

**Issue by binayshaw7777** [atharvakale31/Face_Recognition_Android#22]
I would like to design new Logo for the App.

**Comment by atharvakale31** [comment]
Sure dude, go ahead!

**Comment by binayshaw7777** [comment]
> Sure dude, go ahead!

Okay, cool. I'll share some designs by this week.

**Comment by binayshaw7777** [comment]
I came up with these 3 designs.

![image](https://user-images.githubusercontent.com/62587060/164980845-616ad762-afe5-4f96-9ce6-0378f126bb64.png)

Can you assign this issue to me?
