### ISSUE TITLE
Make it a library(if possible)

### ISSUE THREAD

**Issue by uzariustics123** [atharvakale31/Face_Recognition_Android#23]
Is there a possibility to make this a library? So that we can easily import this to any project and using only APIs?

**Comment by uzariustics123** [comment]
btw this is a very nice project👌

**Comment by atharvakale31** [comment]
Hey @uzariustics123 ,
 Thank You!
 I had this thought too! It is possible to convert this into a little library but I haven't really explored it. 
 It will make the import easy but on the other side, I think it will make it harder for the developer to customize the code.
