### ISSUE TITLE
How can we save photo on web Database & retrieve for face recognition 

### ISSUE THREAD

**Issue by sasikanta04** [atharvakale31/Face_Recognition_Android#25]
How this photo

**Comment by atharvakale31** [comment]
We do not save the photo anyways. We save the face embeddings (1D array). You can save and retrieve this from a Database.

**Comment by Omkarrr** [comment]
where are the face embedding getting stored in your application..sorry I am a beginner

**Comment by atharvakale31** [comment]
The face embeddings are getting stored using Shared Preferences, you can refer to the comments in the code to know where it is happening.
