### ISSUE TITLE
Detection issue

### ISSUE THREAD

**Issue by mohdafroz** [atharvakale31/Face_Recognition_Android#26]
I have added 2 capture images and when I try to find it shows the names of both for 1 face 
Can you please check the video which I have recorded 
You can find below the link to the video please check 
https://drive.google.com/file/d/1ycr6ss276ByiBjpKgYUKfRgmI8-vdmPG/view?usp=sharing

**Comment by atharvakale31** [comment]
Hey @mohdafroz ,
You can try to add the faces again (preferably a clear image from the camera).
You can also tweak the hyperparameters (available in action menu) to increase the strictness of recognition.
