### ISSUE TITLE
How can we detect is photo or real person?

### ISSUE THREAD

**Issue by rranjithkumar100** [atharvakale31/Face_Recognition_Android#27]
Hi Atharva, 

First, thanks for the your efforts to improve the app efficiency. 

My question: 
Can we detect it's a photo or a real person?  
Because I want only real person validation.

**Comment by rranjithkumar100** [comment]
Hi Atharva,

Any update on this? If you give hints it will helpful

**Comment by atharvakale31** [comment]
Hey @rranjithkumar100 ,

It should be possible if a model with liveliness detection is added before the recognition is done.

**Comment by rranjithkumar100** [comment]
@atharvakale31  Thanks for the hints. I will proceed further more with your hint.

**Comment by roshannsharma** [comment]
> Hi Atharva,
> 
> First, thanks for the your efforts to improve the app efficiency.
> How can we detect is photo or real person?
> My question: Can we detect it's a photo or a real person? Because I want only real person validation.

**Comment by roshannsharma** [comment]
How can we detect is photo or real person?
