### ISSUE TITLE
How can i get the tflite file? 

### ISSUE THREAD

**Issue by howell0203** [atharvakale31/Face_Recognition_Android#29]
Did tflite file is tranfered from pb file or ckpt flie which trained by mobilefacenet you have listed in README

**Comment by howell0203** [comment]
ok i got it, just like what i said behind.  And the most important is to change OUTPUT size same with ur tflite model 
 in  MainAcivity.java.(the input size & output size of tflite model can be seen in netron.app)

**Comment by howell0203** [comment]
Thank u~~ for ur excellent code which helps me alot

**Comment by atharvakale31** [comment]
Appreciate it.
Thanks.
