### ISSUE TITLE
Where is image saved ?

### ISSUE THREAD

**Issue by Akmalfirdaus** [atharvakale31/Face_Recognition_Android#3]
Hello, sir. May I ask, where is the image saved after we recognize the face?

**Comment by atharvakale31** [comment]
@Akmalfirdaus Hey, the image is not saved after the face is recognized. It only detects the faces in the current frame. If you want to save the image when a face is detected, you can easily make those changes.

**Comment by Akmalfirdaus** [comment]
> @Akmalfirdaus Hey, the image is not saved after the face is recognized. It only detects the faces in the current frame. If you want to save the image when a face is detected, you can easily make those changes.

Thank you very much, for your reply. I want to ask again, means whether the features of the training are the same? it's not saved the images?

**Comment by atharvakale31** [comment]
@Akmalfirdaus Our model outputs face embeddings(array of numbers), whenever a face is added. Those embedding are saved when clicked on the save button. Then whenever a face is detected new embeddings are created by the model and those are compared to the saved embeddings by nearest neighbor search and the name associated with the nearest neighbor is displayed. Remember we do not train the model again and again.

**Comment by Akmalfirdaus** [comment]
> @Akmalfirdaus Our model outputs face embeddings(array of numbers), whenever a face is added. Those embedding are saved when clicked on the save button. Then whenever a face is detected new embeddings are created by the model and those are compared to the saved embeddings by nearest neighbor search and the name associated with the nearest neighbor is displayed. Remember we do not train the model again and again.

means, can I add it in firebase? I mean the images? because I want to add/save it in firebase.
 then, can you show me how to add/save the images in firebase? it will be helpful

**Comment by atharvakale31** [comment]
@Akmalfirdaus Currently everything is done locally.No images are needed to be saved.If you want to save face embedding on firebase that can be done but it will affect the performance a lot thus not recommended.I would suggest to go through the code and understand the flow first.
