### ISSUE TITLE
How to improve the accuracy of the model ?

### ISSUE THREAD

**Issue by raghavzns** [atharvakale31/Face_Recognition_Android#33]
HI Atharv,

I can see some false detections when the person has beard. How can we improve the accuracy in such cases ? Do we need to train on additional dataset or what ?
Please suggest

**Comment by vasantharaj1972** [comment]
You can improve accuracy in two ways. 1. distance value can be reduced to 0.6/0.7       2.  add flashlight in front of camera for fast recognition.

**Comment by raghavzns** [comment]
Thanks @vasantharaj1972 
Can you pls explain the meaning of the decimal value ? Does higher decimal mean strict matching and better accuracy ?

**Comment by vasantharaj1972** [comment]
The decimal value is a calculated difference value between the captured
image and the prestored images values. The much is smaller the difference
value, so called distant value, that much accuracy of
predicting/recognizing the image

**Comment by rsingh2083** [comment]
@vasantharaj1972 thanks ,I'll reduce the value to .5 
Also can you point out the source file where this value needs to be edited ?

**Comment by vasantharaj1972** [comment]
[image: image.png]

**Comment by atharvakale31** [comment]
Hey,
To recognize a person with a beard, you will have to decrease the 'strictness' of the model.
This would mean that you are decreasing the accuracy of the model (increasing the distance (the decimal value mentioned above) corresponds to reducing the model's accuracy).
This way you will get more false positives.
In the end, it's a trade-off, if you are to work with the existing model, you will have to find a sweet spot for the strictness.

Distance Value:
I added the functionality to edit this value in the app itself. You will find that in the Actions tab.
The developer mode will help you find the value you need.


Thanks.
