### ISSUE TITLE
how to implement this in react native, please help

### ISSUE THREAD

**Issue by timotismjntk** [atharvakale31/Face_Recognition_Android#34]

**Comment by atharvakale31** [comment]
Hey,
Sorry, I don't have experience working with React Native.

**Comment by timotismjntk** [comment]
Hehe no problem bro @atharvakale31, I've already done it

Demo apk: https://drive.google.com/file/d/1YiWkSAIySinjmj_0g0c7Rm_E0WNyhqig/view?usp=drivesdk
