### ISSUE TITLE
Where the line of codes that actually image are saved for while ?

### ISSUE THREAD

**Issue by Akmalfirdaus** [atharvakale31/Face_Recognition_Android#5]
Hello sir, may I ask? ... I'm still confused, can you show me where is the line of codes that actually images are saved for a while?

**Comment by atharvakale31** [comment]
Again as I previously stated, we do not store images rather we store the embeddings of the image created by the model(this is done in real-time and hence no images are saved). I have put comments in the code where each step is done. Do check that out.
