### ISSUE TITLE
Which face detector (python) used for this case?

### ISSUE THREAD

**Issue by ruanjiyang** [atharvakale31/Face_Recognition_Android#7]
Dear Atharva Kale :

thanks very much for your great work.

I want to test the accuracy for this mobile_face_net.tflite , so I builded up a python runtime for it to test hundreds photos.  But I don't know which python face detector can be used for it?  could you let me know?  thanks!

**Comment by atharvakale31** [comment]
Hello there, thank you!!
This model is based on the research paper that I have linked in the readme section. To quote from the paper,

> Our single MobileFaceNet of 4.0MB size
> achieves 99.55% accuracy on LFW and 92.59% TAR@FAR1e-6 on MegaFace,
> which is even comparable to state-of-the-art big CNN models of hundreds MB
> size

They report accuracy better than other state-of-art CNN models.If you still want to test it, you will need to detect a face ->crop it out(by bounding box)->feed it to tflite model.
For detecting faces you can use cv2, mtcnn, dlibs etc.
