### ISSUE TITLE
how to add box on faces.

### ISSUE THREAD

**Issue by shingadesy21** [atharvakale31/Face_Recognition_Android#8]
I'm trying to add box on faces with person name. but can't set it properly.

**Comment by atharvakale31** [comment]
Hey, 
  Sorry I saw this late. I haven't dived deep into the Graphical Interface part.Although here is something you can refer to, https://medium.com/@estebanuri/real-time-face-recognition-with-android-tensorflow-lite-14e9c6cc53a5 .
